### ISSUE TITLE
Technical review

### ISSUE THREAD

**Issue by HelgaListopad** [nsafronova/webixTest#1]
Здравствуйте и большое спасибо за то, что выполнили тестовое!

Результат выглядит хорошо, но есть некоторые вещи, которые можно упростить - для них я оставляю комментарии с примерами.
Это не запрос на обязательные правки. На своё усмотрение Вы можете либо внести изменения в код, либо оставить как есть.

С небольшими изменениями пример может выглядеть так:
https://snippet.webix.com/xjrmv8v0

Ниже я поясню основные изменения: 

<details>
<summary>Размерность</summary>
<br/>

Желательно, чтобы центральная часть (row2) занимала всё доступное пространство.
По умолчанию, если у компонентов нет своих размеров, они подстраиваются под свободное место, но здесь этого не проиходит из-за двух факторов:
- у формы внутри только элементы с фиксированной высотой (текстовые поля и кнопки), и её общая высота подстраивается под них,
- у таблицы есть свойство `autoheight`
https://github.com/nsafronova/webixTest/blob/72bd154d0003a4bc9588804f44b539b1a324523d/index.html#L68

И то, и другое заставляет всю строку сжиматься под минимально возможный размер.
Решить это можно, убрав `autoheight` и добавив spacer (`{ }`) последним элементом в форму.

</details>

Все остальные изменения в snippet'e косметические и сделаны просто для того, чтобы показать оптимальные варианты. Например:
- в row1 лучше использовать toolbar. Ваши css-селекторы написаны без ошибок, но для toolbar также есть [тёмный стиль](https://docs.webix.com/desktop__toolbar.html#darktheme), который всё немного упрощает;
- стили для sidebar изменены с учётом selection;
- кнопка "Connected" заменена на label:
```js
{
  view:"label", 
  align: "center",
  label:"<span class='webix_icon wxi wxi-check'></span>Connected", 
  css: "connect_label",
}
```
У кнопки есть лишние стили на hover, a её функционал сложнее того, что нужно в этом месте.

Также я рекомендовала бы переходить на `let`/`const` вместо `var`, а при подключении файлов использовать относительные пути _внутри_ проекта:
https://github.com/nsafronova/webixTest/blob/72bd154d0003a4bc9588804f44b539b1a324523d/index.html#L9-L10
Путь в Вашем коде будет всегда строиться от корня, и если этот проект лежит глубже (например, `localhost/reviews/webixTest-main/`), попытка получить эти файлы выдаст 404. 
Надёжнее использовать путь относительно index.html: `./style.css`.
https://stackoverflow.com/a/33774151

Спасибо!

**Comment by nsafronova** [comment]
Здравствуйте! Большое спасибо, что уделили время моему решению. Со всеми правками я полностью согласна, обязательно внесу их все в свой код!
